[package]
name = "zjpane"
version = "0.2.0"
authors = ["Christophe MASSOLIN <info@chrsmsln.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.41.2"
chrono = "0.4.0"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
shlex = "1.3.0"

[features]
tracing = []
