[package]
name = "zjpane"
version = "0.1.0"
authors = ["Christophe MASSOLIN <info@chrsmsln.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.40.0"
chrono = "0.4.0"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"

[features]
tracing = []
